config/routes.rb
Rails.application.routes.draw do
    resources :portfolios, except: [:show]
    get 'angular-items', to: 'portfolios#angular'
    get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

    get 'about', to: 'pages#about'
    get 'contact', to: 'pages#contact'

    resources :blogs

    root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    enum status: { draft: 0, published: 1 }
    extend FriendlyId
    friendly_id :title, use: :slugged
    
    validates_presence_of :title, :body

    belongs_to :topic

end

app/models/concerns/placeholder.rb
module Placeholder
    extend ActiveSupport::Concern

    def self.image_generator(height:, weight:)
        "http://via.placeholder.com/#{height}x#{weight}"
    end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }
    includes Placeholder
    validates_presence_of :title, :body, :subtitle, :main_image, :thumb_image

    def self.angular
        where(subtitle: "Angular")
    end

    scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height: '600', weight: '400')
        self.thumb_image ||= Placeholder.image_generator(height: '350', weight: '250')
    end
end

app/models/skill.rb
class Skill < ApplicationRecord
    includes Placeholder
    validates_presence_of :title

    def set_defaults
        self.badge ||= Placeholder.image_generator(height: '250', weight: '250')

    end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates_presence_of :title

    has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
        @portfolio_items = Portfolio.all
    end

    def angular
        @angular_portfolio_items = Portfolio.angular
    end

    def new
        @portfolio_items = Portfolio.new
        3.times { @portfolio_items.technologies.build }
    end

    def create
        @portfolio_items = Portfolio.new(params.require(:portfolio).permit(:title, :subtitle, :body,
            technologies_attributes: [:name]
        ))
        respond_to do |format|
            if @portfolio_items.save
                format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
                format.json { render :show, status: :created, location: @portfolio_items }
            else
                format.html { render :new }
                format.json { render json: @portfolio_items.errors, status: :unprocessable_entity }
            end
        end
    end

    def edit
        @portfolio_items = Portfolio.find(params[:id])
    end


    def update
        @portfolio_items = Portfolio.find(params[:id])
        respond_to do |format|
            if @portfolio_items.update(params.require(:portfolio).permit(:title, :subtitle, :body))
                format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
                format.json { render :show, status: :ok, location: @portfolio_items }
            else
                format.html { render :edit }
                format.json { render json: @portfolio_items.errors, status: :unprocessable_entity }
            end
        end
    end


    def show
        @portfolio_items = Portfolio.find(params[:id])
    end

    def destroy
        #Perform the lookup
        @portfolio_items = Portfolio.find(params[:id])

        #Destroy/Delete the record
        @portfolio_items.destroy

        #Redirect
        respond_to do |format|
            format.html { redirect_to portfolios_url, notice: 'Blog was successfully destroyed.' }
            format.json { head :no_content }
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :blog_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevcampThanhHai</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Homepage</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<table>
  <thead>
    <th>ID</th>
    <th>Title</th>
    <th>Bodies</th>
    <th>Created_At</th>
    <th>Updated_At</th>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= post.created_at %></td>
        <td><%= post.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= @posts.inspect %>

<table>
  <thead>
  <th>ID</th>
  <th>Title</th>
  <th>Percent Utilized</th>
  <th>Created_At</th>
  <th>Updated_At</th>
  </thead>
  <tbody>
  <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.id %></td>
        <td><%= skill.title %></td>
        <td><%= skill.percent_utilized %></td>
        <td><%= skill.created_at %></td>
        <td><%= skill.updated_at %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create new Portfolio Item", new_portfolio_url %>

<% @angular_portfolio_items.each do |portfolioitem| %>
    <h2> <%= link_to portfolioitem.title, portfolio_show_path(portfolioitem) %> </h2>
    <p> <%= portfolioitem.subtitle %> </p>
    <p> <%= portfolioitem.body %> </p>
    <p> <%= portfolioitem.main_image %> </p>
    <p> <%= image_tag portfolioitem.thumb_image unless portfolioitem.thumb_image.nil? %> </p>
    <p> <%= portfolioitem.created_at %> </p>
    <p> <%=  portfolioitem.updated_at %> </p>
    <button><%= link_to "Edit", edit_portfolio_path(portfolioitem.id) %></button>
    <button><%= link_to 'Delete Portfolio Item', portfolio_path(portfolioitem), method: :delete, data: { confirm: 'Are you sure?' } %></button>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit this Portfolio Item</h1>

<%= form_with(model: @portfolio_items, local: true) do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :portfolio_title %>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, id: :portfolio_subtitle %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body, id: :portfolio_body %>
    </div>

    <div class="field">
      <%= form.label :main_image %>
      <%= form.text_field :main_image, id: :main_image %>
    </div>

    <div class="field">
      <%= form.label :thumb_image %>
      <%= form.text_area :thumb_image, id: :thumb_image %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create new Portfolio Item", new_portfolio_url %>

<% @portfolio_items.each do |portfolioitem| %>
    <h2> <%= link_to portfolioitem.title, portfolio_show_path(portfolioitem) %> </h2>
    <p> <%= portfolioitem.subtitle %> </p>
    <p> <%= portfolioitem.body %> </p>
    <p> <%= portfolioitem.main_image %> </p>
    <p> <%= image_tag portfolioitem.thumb_image unless portfolioitem.thumb_image.nil? %> </p>
    <p> <%= portfolioitem.created_at %> </p>
    <p> <%=  portfolioitem.updated_at %> </p>
    <button><%= link_to "Edit", edit_portfolio_path(portfolioitem.id) %></button>
    <button><%= link_to 'Delete Portfolio Item', portfolio_path(portfolioitem), method: :delete, data: { confirm: 'Are you sure?' } %></button>
<% end %>

app/views/portfolios/new.html.erb
<h1>Create New Portfolio Item</h1>

<%= form_with(model: @portfolio_items, local: true) do |form| %>
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title, id: :portfolio_title %>
    </div>

    <div class="field">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, id: :portfolio_subtitle %>
    </div>

    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body, id: :portfolio_body %>
    </div>

    <ul>
      <%= form.fields_for :technologies do |technology_form| %>
        <li>
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name %>
        </li>
      <% end %>
    </ul>

    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/portfolios/show.html.erb
<%= image_tag @portfolio_items.main_image %>

<h1><%= @portfolio_items.title %></h1>

<em><%= @portfolio_items.subtitle %></em>

<p><%= @portfolio_items.body %></p>

<h2>Technologies Used:</h2>

<%= @portfolio_items.technologies.each do |t| %>
    <p><%= t.name %></p>
<% end %>